<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RegressionTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>55176a13-f97b-4963-b62d-ef608b8fc708</testSuiteGuid>
   <testCaseLink>
      <guid>553de2ce-c076-451c-bae5-99b58bde6b6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LoginLogoutTest/LoginTest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>69649ee2-a2ca-4048-b0f1-bee68a9f1834</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LoginLogoutTest/LogoutTest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a02e18d8-8813-45c1-a006-260fbbb9dcd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CreateTripTest/CreateTripByName</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>96f0fc9a-40d3-49ec-b4e5-1db47b03f1aa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CreateTrip/TripInfoTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>96f0fc9a-40d3-49ec-b4e5-1db47b03f1aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TripName</value>
         <variableId>00761283-a2fe-4137-b76f-e6a73b758bf6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5526bbc-e5c9-4e4c-b91f-0f30e0a50a16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CreateTripTest/CreateTripByLocation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8e37cfee-d11e-4bf3-95fe-62478f84594d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CreateTrip/TripInfoTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8e37cfee-d11e-4bf3-95fe-62478f84594d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Location</value>
         <variableId>a05d3185-daf7-4043-ae3d-dd4e1eeeb5d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20894a37-6ac0-4064-b096-cc28d5c52c97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CreateTripTest/CreateTripByAll</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8ae3d686-3880-450a-9135-596090afa3d7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CreateTrip/TripInfoTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8ae3d686-3880-450a-9135-596090afa3d7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TripName</value>
         <variableId>83aa5153-1fef-493e-9266-8780f57bef1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8ae3d686-3880-450a-9135-596090afa3d7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Location</value>
         <variableId>7e79505d-6ef7-4711-94a1-54afa7310ce7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a98fd24d-3676-4129-94fc-268646fbd647</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CreateIdeaTest/CreateIdeaByName</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4c02f592-daf8-4b41-bec8-d0a9a47bec51</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CreateTrip/TripInfoTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4c02f592-daf8-4b41-bec8-d0a9a47bec51</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IdeaName</value>
         <variableId>ddc07004-40e6-4dad-866d-941ddf3ffde8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>595206e6-1f53-43e1-9322-f10bcab06e28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CreateIdeaTest/CreateIdeaByLocation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4be286b8-60ab-4bb2-a4e6-9ae30b5fccad</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CreateTrip/TripInfoTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4be286b8-60ab-4bb2-a4e6-9ae30b5fccad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Location</value>
         <variableId>08577b9f-f49f-4e8b-9279-0594bd24af72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d216f88-01c1-4654-a9c0-3fdac4be8767</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CreateIdeaTest/CreateIdeaByAll</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>98d52b52-28f0-4acf-99cb-31a2a3ada169</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CreateTrip/TripInfoTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>98d52b52-28f0-4acf-99cb-31a2a3ada169</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IdeaName</value>
         <variableId>1439aa18-dcd7-43b7-b87f-e386a190bb9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>98d52b52-28f0-4acf-99cb-31a2a3ada169</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Location</value>
         <variableId>8a6c02a6-81af-4c97-a394-3f1091740e78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c45c9def-e406-4325-8fd5-f3df23755f04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CreateActivityTest/ActivityByPick</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6e2eb224-a864-4a2c-acaf-8d51ee21c93e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CreateTrip/TripInfoTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>6e2eb224-a864-4a2c-acaf-8d51ee21c93e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TripName</value>
         <variableId>f35796d5-702b-4001-80f1-9f01b1589e21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e7592e6-a40d-4da3-abf4-54368a59bab5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CreateActivityTest/ActivityByType</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4956dbb3-022c-4d46-b428-56fe9f0e7aa7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CreateTrip/TripInfoTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4956dbb3-022c-4d46-b428-56fe9f0e7aa7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TripName</value>
         <variableId>55f8419d-78ee-465c-a57e-fcae46114898</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
