<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddFriendToTrip</name>
   <tag></tag>
   <elementGuidId>f991b9d0-a04d-47d3-9265-f32a87a50717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h5[@class='vcenter'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h5[@class='vcenter'])[1]</value>
   </webElementProperties>
</WebElementEntity>
